CREATE TABLE IF NOT EXISTS "Users" (
    "ID" TEXT PRIMARY KEY,
    "NAME" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL UNIQUE,
    "PASS" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "Groups" (
    "OWNER_ID" TEXT NOT NULL,
    "ID" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "PARENT_ID" TEXT,
    "CREATED_AT" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("OWNER_ID", "ID"),
    FOREIGN KEY ("OWNER_ID", "PARENT_ID")
        REFERENCES "Groups" ("OWNER_ID", "ID")
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS "Tasks" (
    "OWNER_ID" TEXT NOT NULL,
    "ID" TEXT NOT NULL,
    "GROUP_ID" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "DESCRIPTION" TEXT NOT NULL,
    "MAX_PRICE" REAL NOT NULL DEFAULT 0 CHECK ("MAX_PRICE" >= 0),
    "CURRENT_PRICE" REAL NOT NULL DEFAULT 0 CHECK ("CURRENT_PRICE" >= 0),
    "IS_COMPLETE" INTEGER NOT NULL DEFAULT 0 CHECK ("IS_COMPLETE" IN (0, 1)),
    "CREATED_AT" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("OWNER_ID", "ID"),
    FOREIGN KEY ("OWNER_ID", "GROUP_ID")
        REFERENCES "Groups" ("OWNER_ID", "ID")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UserSettings" (
    "OWNER_ID" TEXT PRIMARY KEY,
    "THEME" TEXT NOT NULL DEFAULT 'light' CHECK ("THEME" IN ('light', 'dark'))
);

CREATE INDEX IF NOT EXISTS "IX_Groups_Owner_Parent"
    ON "Groups" ("OWNER_ID", "PARENT_ID");
CREATE INDEX IF NOT EXISTS "IX_Tasks_Owner_Group"
    ON "Tasks" ("OWNER_ID", "GROUP_ID");
